### ISSUE TITLE
NameError: name 'system' is not defined

### ISSUE THREAD

**Issue by Meytiz** [new92/IAM#11]
\IAM\IAM.py:197: SyntaxWarning: invalid escape sequence '\ '
  print(f"{green}[*] Path must contain: / or \ ")
[!] WARNING: Not all packages used in IAM have been installed !
[+] Ignoring warning...
Traceback (most recent call last):
  File "C:\Users\m.soleimanzadeh\Downloads\IAM\IAM.py", line 36, in <module>
    from rich.align import Align
ModuleNotFoundError: No module named 'rich'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m.soleimanzadeh\Downloads\IAM\IAM.py", line 117, in <module>
    system("pip3 install -r requirements.txt")
    ^^^^^^
NameError: name 'system' is not defined

how Fix that's?

**Comment by new92** [comment]
Hey @Meytiz did you follow the [installation process](https://github.com/new92/IAM#installation-) ? Also, made some changes now try updating the script using this command:
```bash
cd IAM
git pull
```

**Comment by Meytiz** [comment]
Traceback (most recent call last):
  File "C:\Users\m.soleimanzadeh\Downloads\IAM\IAM.py", line 36, in <module>
    from rich.align import Align
ModuleNotFoundError: No module named 'rich'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m.soleimanzadeh\Downloads\IAM\IAM.py", line 116, in <module>
    system("pip3 install -r requirements.txt")
    ^^^^^^
NameError: name 'system' is not defined

**Comment by Meytiz** [comment]
windows installer.
how fix that's.

**Comment by new92** [comment]
Ok let me check it and I'll get back to you.
