### ISSUE TITLE
Complete installation guide

### ISSUE THREAD

**Issue by Meytiz** [new92/IAM#13]
I tried to install the source on the server and Windows, but I still had problems!
Is it possible to learn this source completely?

**Comment by new92** [comment]
Hey @Meytiz, just made an update so the second issue (NameError: name 'Live' is not defined. Did you mean: 'like'?) should be resolved. As for the first one, can you provide me with a screenshot in order to betten understand the error messages you're receiving ?

**Comment by Meytiz** [comment]
C:\Users\M!IND\Downloads\IAM>python3 cookies.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by Meytiz** [comment]
![Uploading Screenshot (3).png…]()

**Comment by new92** [comment]
Ok so you need to edit the environment's variables in order to resolve the `python not found` error. For the second one try entering this command:
`pip install -r ./files/requirements.txt`

**Comment by Meytiz** [comment]
![Screenshot (5)](https://github.com/new92/IAM/assets/73021060/6f784e34-2a38-42a1-8ef1-6c13eb5c4c21)

**Comment by Meytiz** [comment]
C:\Users\M!IND\Downloads\IAM>py cookies.py
Using cookies from C:\Users\M!IND/AppData/Roaming/Mozilla/Firefox/Profiles\8sc9n5ae.default-release\cookies.sqlite.
Cookie import failed: JSON Query to graphql/query: HTTP error code 401.

**Comment by Meytiz** [comment]
![Screenshot (6)](https://github.com/new92/IAM/assets/73021060/e5f00614-09bd-40d4-906a-20820b1bd0d8)
how fix that?

**Comment by Meytiz** [comment]
![Screenshot (6)](https://github.com/new92/IAM/assets/73021060/f843a6a1-570b-4971-9a84-7f316b9ef706)
where is the problem from?

**Comment by new92** [comment]
Hey @Meytiz check [this tutorial](https://realpython.com/add-python-to-path/) to resolve the python not found issue. In order to resolve the second issue (Cookie import failed: ...) log in to your Instagram account from firefox. Then enter the command `python3 cookies.py` in your terminal and finally enter: `python3 IAM.py` again in your terminal.

**Comment by Meytiz** [comment]
I did this. But the problem still exists.

**Comment by new92** [comment]
Ok give me a couple of seconds to fix it and I'll let you know.

**Comment by new92** [comment]
Try again now maybe. I changed the login method. With the same procedure. Login to your instagram acc via firefox, `python3 cookies.py` and `python3 IAM.py`

**Comment by Meytiz** [comment]
ok, git pull yeah?

**Comment by new92** [comment]
Exactly !

**Comment by new92** [comment]
And let me know

**Comment by Meytiz** [comment]
![Screenshot (9)](https://github.com/new92/IAM/assets/73021060/5c89b195-9e1d-4a02-b2da-5798fe7cbdab)
:(

**Comment by new92** [comment]
Shit. Ok I'll try to fix it and I'll get back to you in a couple of hours.

**Comment by Meytiz** [comment]
tnx bro

**Comment by Meytiz** [comment]
fixed man?

**Comment by new92** [comment]
Hey @Meytiz sorry it's not ready yet. It's pretty big script. I will try to fix it and upload it later today or tomorrow.

**Comment by Meytiz** [comment]
:(

**Comment by new92** [comment]
Hey @Meytiz I'm really sorry but I truly can't work on your request right now, I'll try to fix it this or the next week.

**Comment by ShivamB25** [comment]
> Hey @Meytiz I'm really sorry but I truly can't work on your request right now, I'll try to fix it this or the next week.

python3 cookies.py
Using cookies from /Users/{usernmae}/Library/Application Support/Firefox/Profiles/ghyuqd3e.default/cookies.sqlite.

Cookie import failed: JSON Query to graphql/query: HTTP error code 401.

**Comment by Meytiz** [comment]
use py cookies.py

**Comment by Meytiz** [comment]
@new92 :(((((((((((

**Comment by ShivamB25** [comment]
> use py cookies.py

hey i am on macos. used python instead of python3. same issue

> python3 cookies.py
Using cookies from /Users/{myusername}/Library/Application Support/Firefox/Profiles/ghyuqd3e.default/cookies.sqlite.
Cookie import failed: JSON Query to graphql/query: HTTP error code 401.

**Comment by new92** [comment]
Hey @Meytiz so sorry for the delay 😭 I fixed the bug and the script works just fine ! Tested it myself 👍

**Comment by new92** [comment]
Hey @ShivamB25 ok so you need to firstly download Firefox (if not already installed) and login to your instagram account before running `cookies.py` and `IAM.py` scripts.

**Comment by Meytiz** [comment]
I tested it today but it didn't work for me!

**Comment by Meytiz** [comment]
[::] Posts to like/unlike (num) >>> 10
Traceback (most recent call last):
  File "C:\Users\M!IND\Downloads\IAM-main\IAM-main\IAM.py", line 3341, in <module>
    main()
  File "C:\Users\M!IND\Downloads\IAM-main\IAM-main\IAM.py", line 2619, in main
    browser = webdriver.Chrome()
              ^^^^^^^^^
NameError: name 'webdriver' is not defined

C:\Users\M!IND\Downloads\IAM-main\IAM-main>

**Comment by new92** [comment]
@Meytiz try again now, I fixed the problem. Just make sure you update IAM before running it. Using the git pull command.

**Comment by Meytiz** [comment]
[!] WARNING: Not all packages used in IAM have been installed !

**Comment by Meytiz** [comment]
Traceback (most recent call last):
  File "C:\Users\M!IND\Downloads\IAM-main\IAM-main\IAM.py", line 117, in <module>
    init(autoreset=True)
    ^^^^
NameError: name 'init' is not defined. Did you mean: 'int'?

**Comment by new92** [comment]
@Meytiz fixed the bugs try one more time please

**Comment by Meytiz** [comment]
[::] Posts to like/unlike (num) >>> 10
Traceback (most recent call last):
  File "C:\Users\M!IND\Downloads\IAM\IAM.py", line 3341, in <module>
    main()
  File "C:\Users\M!IND\Downloads\IAM\IAM.py", line 2619, in main
    browser = webdriver.Chrome()
              ^^^^^^^^^
NameError: name 'webdriver' is not defined

**Comment by new92** [comment]
Now ?

**Comment by Meytiz** [comment]
yeap

**Comment by Meytiz** [comment]
Still the same error

**Comment by Meytiz** [comment]
[::] Posts to like/unlike (num) >>> 10
Traceback (most recent call last):
  File "C:\Users\M!IND\Downloads\IAM\IAM.py", line 3343, in <module>
    main()
  File "C:\Users\M!IND\Downloads\IAM\IAM.py", line 2621, in main
    browser = webdriver.Chrome()
              ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Chrome'

**Comment by new92** [comment]
What about now ?

**Comment by Meytiz** [comment]
[::] Users to follow (num) >>> 10
[?] Users to follow their followers (num) >>> 1
[::] Username No1 >>> ft360_ir
[✓] User added.
[+] Initiating following process...
[!] Error !
[*] Error message ==> name 'bot' is not defined
[1] Return to menu
[2] Exit
[::] Number (from the above ones) >>>

**Comment by new92** [comment]
Hey @Meytiz let me fix it and I'll get back to you
